{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dada-cloud-console.fullname" . }}-backend
  labels:
    {{- include "dada-cloud-console.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: http
  selector:
    {{- include "dada-cloud-console.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
{{- end }}
