apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dada-cloud-console.fullname" . }}-config
  labels:
    {{- include "dada-cloud-console.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.backend.env }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- range $key, $value := .Values.frontend.env }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
