{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dada-cloud-console.fullname" . }}-frontend
  labels:
    {{- include "dada-cloud-console.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: http
  selector:
    {{- include "dada-cloud-console.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
{{- end }}
