{{- if and .Values.backend.enabled (not .Values.backend.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dada-cloud-console.fullname" . }}-backend
  labels:
    {{- include "dada-cloud-console.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- range $key, $value := .Values.backend.secret }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
